name: Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout
        uses: actions/checkout@v7

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: lts/krypton
          cache: 'npm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install
        run: npm ci

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build

      - name: Upload NPM Artifact
        uses: actions/upload-artifact@v7
        with:
          name: 'dist'
          path: 'dist'
          if-no-files-found: error

      - name: Publish NPM
        run: npm publish --provenance --access public --tag ${{ contains(github.ref_name, '-') && 'beta' || 'latest' }}

      - name: Prepare Pages Artifact
        run: |
          mkdir -p pages
          cp -r src/main/resources/* pages/
          cp dist/bundle.head.json pages/
          cp dist/bundle.json pages/

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: pages/

      - name: Create Release
        uses: softprops/action-gh-release@v3
        with:
          draft: true
          files: 'dist/*'


  pages:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
